/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/Desktop/speech_ws/src/trollnode-kinect_img/msg/Expression.msg
 *
 */


#ifndef TROLLNODE_MESSAGE_EXPRESSION_H
#define TROLLNODE_MESSAGE_EXPRESSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trollnode
{
template <class ContainerAllocator>
struct Expression_
{
  typedef Expression_<ContainerAllocator> Type;

  Expression_()
    : speech()
    , expression()  {
    }
  Expression_(const ContainerAllocator& _alloc)
    : speech(_alloc)
    , expression(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _speech_type;
  _speech_type speech;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _expression_type;
  _expression_type expression;




  typedef boost::shared_ptr< ::trollnode::Expression_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trollnode::Expression_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Expression_

typedef ::trollnode::Expression_<std::allocator<void> > Expression;

typedef boost::shared_ptr< ::trollnode::Expression > ExpressionPtr;
typedef boost::shared_ptr< ::trollnode::Expression const> ExpressionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trollnode::Expression_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trollnode::Expression_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace trollnode

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'trollnode': ['/home/viki/Desktop/speech_ws/src/trollnode-kinect_img/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::trollnode::Expression_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trollnode::Expression_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trollnode::Expression_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trollnode::Expression_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trollnode::Expression_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trollnode::Expression_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trollnode::Expression_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64c25de9407ff13a659a42faaadb6ea1";
  }

  static const char* value(const ::trollnode::Expression_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64c25de9407ff13aULL;
  static const uint64_t static_value2 = 0x659a42faaadb6ea1ULL;
};

template<class ContainerAllocator>
struct DataType< ::trollnode::Expression_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trollnode/Expression";
  }

  static const char* value(const ::trollnode::Expression_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trollnode::Expression_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string speech		#The troll will say this out loud. Write normal english.\n\
string expression 	#shortform for the expression, like angry, smile, etc. \n\
\n\
";
  }

  static const char* value(const ::trollnode::Expression_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trollnode::Expression_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speech);
      stream.next(m.expression);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Expression_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trollnode::Expression_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trollnode::Expression_<ContainerAllocator>& v)
  {
    s << indent << "speech: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.speech);
    s << indent << "expression: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.expression);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TROLLNODE_MESSAGE_EXPRESSION_H
